export const SET_STORIES_HEIGHT = 'SET_STORIES_HEIGHT'

export const SET_THEME_ID = 'SET_THEME_ID'

export const SET_SCROLL_TOP = 'SET_SCROLL_TOP'

export const SET_DETAIL_SHOW = 'SET_DETAIL_SHOW'

export const SET_SIDEBAR_SHOW = 'SET_SIDEBAR_SHOW'

export const SET_FAVORITE_SHOW = 'SET_FAVORITE_SHOW'

export const SET_STORIES_STATE = 'SET_STORIES_STATE'

export const SET_FAVORITE_STORIES = 'SET_FAVORITE_STORIES'

export const SET_NIGHT_MODE = 'SET_NIGHT_MODE'
